<?php

use Faker\Generator as Faker;

$factory->define(App\Linea_dato::class, function (Faker $faker) {
    return [

      'fecha'=>$faker->dateTimeThisYear($max = 'now', $timezone = 'Europe/Paris', $format = 'd-m-Y')->format('Y-m-d'),
      'hora'=>$faker->time($format = 'H:i', $max = 'now', $timezone = 'Europe/Paris') ,
      'linea'=>$faker->randomElement($array = array('A','B')),
      'tt1'=>$faker->numberBetween(120, 130),
      'tt2'=>$faker->numberBetween(37, 45),
      'tt3'=>$faker->numberBetween(230, 240),
      'tt4'=>$faker->numberBetween(260, 275),
      'intensidad_total'=>$faker->numberBetween(240, 350),
      'intensidad_tambor'=>$faker->numberBetween(90, 170),
      'intensidad_ve2'=>$faker->numberBetween(49, 51),
      'total_caudal_entrada_scruber'=>$faker->numberBetween(70000, 79000),
      'total_caudal_salida_scruber'=>$faker->numberBetween(158000, 159000),
      'caudal_recirc_scruber'=>$faker->numberBetween(12, 16),
      'temp_aceite_entrada_tambor'=>$faker->numberBetween(290, 295),
      'presion_salida_tambor'=>$faker->numberBetween(8, 10),
      'presion_entrada_scruber'=>$faker->numberBetween(-10, 5),
      'presion_entrada_condensador'=>$faker->numberBetween(60, 70),
      'presion_salida_condensador'=>$faker->numberBetween(20000, 400000),
      'posicionvalvula_ve2'=>$faker->numberBetween(4, 9),
      'posicionvalvula_purga'=>$faker->randomFloat(1, 1.5, 3),
      'presion_entrada_tambor'=>$faker->numberBetween(14, 26),
      'variador_electrico'=>$faker->randomFloat(2, 15, 20),
      'variador_mecanico'=>0,
      'vueltas_bomba'=>$faker->numberBetween(20, 32),
      'temp_aceite_ent_intercambiador'=>$faker->numberBetween(285, 292),
      'temp_aceite_salida_intercambiador'=>$faker->numberBetween(250, 260),
      'temp_agua_entrada_condensador'=>$faker->numberBetween(40, 50),
      'temp_agua_salida_condensador'=>$faker->numberBetween(50, 60),
      'caudal_agua_a_condensador'=>$faker->numberBetween(60, 90),
      'temp_agua_ent_torre'=>$faker->numberBetween(40, 50),
      'temp_agua_sal_torre'=>$faker->numberBetween(25, 40),
      'caudal_agua_a_torre'=>$faker->numberBetween(60, 80),
      'temp_trabajo_verde'=>$faker->numberBetween(290, 295),
      'temp_quemador_rojo'=>$faker->randomFloat(1, 290, 296),
      'presion_ent_biogas'=>$faker->randomFloat(1, 0.2, 2.2),
      'temp_aceite_ent_caldera_dysp'=>$faker->numberBetween(270, 280),
      'temp_aceite_sal_caldera_dysp'=>$faker->numberBetween(292, 295),
      'temp_humos_caldera_dysp'=>$faker->numberBetween(292, 295),
      'presion_gas_ent_caldera_dysp'=>$faker->randomFloat(1, 4, 4.2),
      'presion_gas_sal_caldera_dysp'=>$faker->randomFloat(1, 1, 1.2),
      'porcentaje_ventilador_cal'=>$faker->numberBetween(30, 40),
      'caudal_lampara'=>$faker->numberBetween(25, 30),
      'valor_lampara_titanium'=>$faker->numberBetween(40, 180),
      'dosificacion_sosa'=>$faker->numberBetween(20, 30),
      'consumo_inst_biogas'=>$faker->randomFloat(1, 190, 220),
      'riqueza_biogas'=>$faker->randomFloat(2, 60, 75),
      'totalizador_biogas'=>$faker->randomFloat(2, 400000, 50000),
      'observaciones'=>$faker->sentence($nbWords = 6, $variableNbWords = true),
      'user_id'=>App\User::all()->random()->id,
    ];
});
